import streamlit as st
import pandas as pd
import pickle
import numpy as np

st.set_page_config(page_title="Loan Approval Predictor", page_icon="🏦", layout="centered")
st.title("🏦 Loan Approval Predictor")
st.caption("Friendly loan eligibility check")

# -------------------------------
# Load model & encoders
# -------------------------------
@st.cache_resource
def load_artifacts():
    with open("random_forest_model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("feature_encoders.pkl", "rb") as f:
        feature_encoders = pickle.load(f)
    with open("target_encoder.pkl", "rb") as f:
        target_encoder = pickle.load(f)
    return model, feature_encoders, target_encoder

model, feature_encoders, target_encoder = load_artifacts()

# -------------------------------
# Helper
# -------------------------------
def encode_input(df):
    for col, encoder in feature_encoders.items():
        if col in df.columns:
            df[col] = encoder.transform(df[col])
    return df

# -------------------------------
# UI
# -------------------------------
st.header("👤 Applicant Info")

col1, col2, col3 = st.columns(3)
with col1:
    no_of_dependents = st.selectbox("Number of Dependents", ["0", "1", "2", "3", "4", "5+"])
    education = st.radio("Education Level", ["Graduate", "Not Graduate"])
with col2:
    self_employed = st.radio("Self Employed?", ["Yes", "No"])
with col3:
    income_annum = st.slider("Income (per annum)", 0, 10000000, 5000000, step=50000)

st.divider()
st.header("🏠 Loan & Assets")

col1, col2 = st.columns(2)
with col1:
    loan_amount = st.slider("Loan Amount", 0, 50000000, 20000000, step=1000000)
    loan_term = st.slider("Loan Term (months)", 1, 60, 12)
    cibil_score = st.slider("CIBIL Score", 0, 900, 700)
with col2:
    residential_assets_value = st.slider("Residential Assets", 0, 50000000, 5000000, step=1000000)
    commercial_assets_value = st.slider("Commercial Assets", 0, 50000000, 5000000, step=1000000)
    luxury_assets_value = st.slider("Luxury Assets", 0, 50000000, 5000000, step=1000000)
    bank_asset_value = st.slider("Bank Assets", 0, 50000000, 5000000, step=1000000)

# -------------------------------
# Prepare DataFrame
# -------------------------------
input_dict = {
    "no_of_dependents": no_of_dependents,
    "education": education,
    "self_employed": self_employed,
    "income_annum": income_annum,
    "loan_amount": loan_amount,
    "loan_term": loan_term,
    "cibil_score": cibil_score,
    "residential_assets_value": residential_assets_value,
    "commercial_assets_value": commercial_assets_value,
    "luxury_assets_value": luxury_assets_value,
    "bank_asset_value": bank_asset_value
}

input_df = pd.DataFrame([input_dict])
input_df = encode_input(input_df)
input_df = input_df[model.feature_names_in_]

# -------------------------------
# Predict
# -------------------------------
st.header("📊 Prediction")
if st.button("🔮 Check Loan Eligibility"):
    pred_encoded = model.predict(input_df)[0]
    pred_label = target_encoder.inverse_transform([pred_encoded])[0]
    proba = model.predict_proba(input_df)[0]
    confidence = np.max(proba)

    if pred_label.lower() == "approved":
        st.success("✅ Loan Approved")
    else:
        st.error("❌ Loan Rejected")

    st.metric("Confidence", f"{confidence:.1%}")
    st.caption("This prediction is generated by a machine learning model and is not financial advice.")
