import streamlit as st
import pandas as pd
import pickle
import numpy as np

# -------------------------------
# Page config
# -------------------------------
st.set_page_config(
    page_title="Loan Approval Predictor",
    page_icon="🏦",
    layout="centered"
)

st.title("🏦 Loan Approval Predictor")
st.caption("Simple, fast, and human-friendly loan eligibility check")

# -------------------------------
# Load model & encoders
# -------------------------------
@st.cache_resource
def load_artifacts():
    with open("random_forest_model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("feature_encoders.pkl", "rb") as f:
        feature_encoders = pickle.load(f)
    with open("target_encoder.pkl", "rb") as f:
        target_encoder = pickle.load(f)
    return model, feature_encoders, target_encoder

model, feature_encoders, target_encoder = load_artifacts()

# -------------------------------
# Helper functions
# -------------------------------
def encode_input(df):
    """Encode all categorical features using the saved encoders"""
    for col, encoder in feature_encoders.items():
        if col in df.columns:
            df[col] = encoder.transform(df[col])
    return df

# -------------------------------
# UI Sections
# -------------------------------
st.header("👤 Applicant Profile")

col1, col2 = st.columns(2)
with col1:
    gender = st.radio("Gender", ["Male", "Female"])
    married = st.radio("Marital Status", ["Yes", "No"])
with col2:
    dependents = st.selectbox("Number of Dependents", ["0", "1", "2", "3+"])
    education = st.radio("Education Level", ["Graduate", "Not Graduate"])

st.divider()

st.header("💼 Employment & Income")
col1, col2 = st.columns(2)
with col1:
    self_employed = st.radio("Self Employed?", ["Yes", "No"])
    applicant_income = st.slider("Applicant Monthly Income", 0, 100000, 5000, step=500)
with col2:
    coapplicant_income = st.slider("Co-Applicant Monthly Income", 0, 100000, 0, step=500)

st.divider()

st.header("🏠 Loan Details")
col1, col2 = st.columns(2)
with col1:
    loan_amount = st.slider("Loan Amount (in thousands)", 10, 700, 150, step=10)
    loan_term = st.selectbox("Loan Term (months)", ["360", "180", "120", "60"])
with col2:
    credit_history = st.radio("Credit History", ["Good", "Bad"])
    property_area = st.radio("Property Location", ["Urban", "Semiurban", "Rural"])

st.divider()

# -------------------------------
# Prepare input DataFrame
# -------------------------------
input_dict = {
    "Gender": gender,
    "Married": married,
    "Dependents": dependents,
    "Education": education,
    "Self_Employed": self_employed,
    "ApplicantIncome": applicant_income,
    "CoapplicantIncome": coapplicant_income,
    "LoanAmount": loan_amount,
    "Loan_Amount_Term": loan_term,
    "Credit_History": credit_history,
    "Property_Area": property_area,
}

input_df = pd.DataFrame([input_dict])

# Encode categorical features
input_df = encode_input(input_df)

# Ensure correct column order
input_df = input_df[model.feature_names_in_]

# -------------------------------
# Prediction
# -------------------------------
st.header("📊 Result")

if st.button("🔮 Check Loan Eligibility", use_container_width=True):
    pred_encoded = model.predict(input_df)[0]
    pred_label = target_encoder.inverse_transform([pred_encoded])[0]

    proba = model.predict_proba(input_df)[0]
    confidence = np.max(proba)

    if pred_label.lower() == "approved":
        st.success("✅ **Loan Approved**")
    else:
        st.error("❌ **Loan Rejected**")

    st.metric("Confidence", f"{confidence:.1%}")
    st.caption("This prediction is generated by a machine learning model and should not be considered financial advice.")
